variables: 
  GLOBAL_VARIABLE: "This is a global variable"
  COMMON_URL: "https://example.com"

stages:         
  - predefined-variables
  - merge-request-variables
  - test
  - deploy

test-variables:      
  stage: predefined-variables
  script:
    - echo "CHAT_CHANNEL=$CHAT_CHANNEL"
    - echo "CHAT_INPUT=$CHAT_INPUT"
    - echo "CHAT_USER_ID=$CHAT_USER_ID"
    - echo "CI=$CI"
    - echo "CI_API_V4_URL=$CI_API_V4_URL"
    - echo "CI_API_GRAPHQL_URL=$CI_API_GRAPHQL_URL"
    - echo "CI_BUILDS_DIR=$CI_BUILDS_DIR"
    - echo "CI_COMMIT_AUTHOR=$CI_COMMIT_AUTHOR"
    - echo "CI_COMMIT_BEFORE_SHA=$CI_COMMIT_BEFORE_SHA"
    - echo "CI_COMMIT_BRANCH=$CI_COMMIT_BRANCH"
    - echo "CI_COMMIT_DESCRIPTION=$CI_COMMIT_DESCRIPTION"
    - echo "CI_COMMIT_MESSAGE=$CI_COMMIT_MESSAGE"
    - echo "CI_COMMIT_REF_NAME=$CI_COMMIT_REF_NAME"
    - echo "CI_COMMIT_REF_PROTECTED=$CI_COMMIT_REF_PROTECTED"
    - echo "CI_COMMIT_REF_SLUG=$CI_COMMIT_REF_SLUG"
    - echo "CI_COMMIT_SHA=$CI_COMMIT_SHA"
    - echo "CI_COMMIT_SHORT_SHA=$CI_COMMIT_SHORT_SHA"
    - echo "CI_COMMIT_TAG=$CI_COMMIT_TAG"
    - echo "CI_COMMIT_TAG_MESSAGE=$CI_COMMIT_TAG_MESSAGE"
    - echo "CI_COMMIT_TIMESTAMP=$CI_COMMIT_TIMESTAMP"
    - echo "CI_COMMIT_TITLE=$CI_COMMIT_TITLE"
    - echo "CI_CONCURRENT_ID=$CI_CONCURRENT_ID"
    - echo "CI_CONCURRENT_PROJECT_ID=$CI_CONCURRENT_PROJECT_ID"
    - echo "CI_CONFIG_PATH=$CI_CONFIG_PATH"
    - echo "CI_DEBUG_TRACE=$CI_DEBUG_TRACE"
    - echo "CI_DEBUG_SERVICES=$CI_DEBUG_SERVICES"
    - echo "CI_DEFAULT_BRANCH=$CI_DEFAULT_BRANCH"
    - echo "CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX=$CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX"
    - echo "CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX=$CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX"
    - echo "CI_DEPENDENCY_PROXY_PASSWORD=$CI_DEPENDENCY_PROXY_PASSWORD"
    - echo "CI_DEPENDENCY_PROXY_SERVER=$CI_DEPENDENCY_PROXY_SERVER"
    - echo "CI_DEPENDENCY_PROXY_USER=$CI_DEPENDENCY_PROXY_USER"
    - echo "CI_DEPLOY_FREEZE=$CI_DEPLOY_FREEZE"
    - echo "CI_DEPLOY_PASSWORD=$CI_DEPLOY_PASSWORD"
    - echo "CI_DEPLOY_USER=$CI_DEPLOY_USER"
    - echo "CI_DISPOSABLE_ENVIRONMENT=$CI_DISPOSABLE_ENVIRONMENT"
    - echo "CI_ENVIRONMENT_NAME=$CI_ENVIRONMENT_NAME"
    - echo "CI_ENVIRONMENT_SLUG=$CI_ENVIRONMENT_SLUG"
    - echo "CI_ENVIRONMENT_URL=$CI_ENVIRONMENT_URL"
    - echo "CI_ENVIRONMENT_ACTION=$CI_ENVIRONMENT_ACTION"
    - echo "CI_ENVIRONMENT_TIER=$CI_ENVIRONMENT_TIER"
    - echo "CI_GITLAB_FIPS_MODE=$CI_GITLAB_FIPS_MODE"
    - echo "CI_HAS_OPEN_REQUIREMENTS=$CI_HAS_OPEN_REQUIREMENTS"
    - echo "CI_JOB_ID=$CI_JOB_ID"
    - echo "CI_JOB_IMAGE=$CI_JOB_IMAGE"
    - echo "CI_JOB_JWT=$CI_JOB_JWT"
    - echo "CI_JOB_JWT_V1=$CI_JOB_JWT_V1"
    - echo "CI_JOB_JWT_V2=$CI_JOB_JWT_V2"
    - echo "CI_JOB_MANUAL=$CI_JOB_MANUAL"
    - echo "CI_JOB_NAME=$CI_JOB_NAME"
    - echo "CI_JOB_NAME_SLUG=$CI_JOB_NAME_SLUG"
    - echo "CI_JOB_STAGE=$CI_JOB_STAGE"
    - echo "CI_JOB_STATUS=$CI_JOB_STATUS"
    - echo "CI_JOB_TIMEOUT=$CI_JOB_TIMEOUT"
    - echo "CI_JOB_TOKEN=$CI_JOB_TOKEN"
    - echo "CI_JOB_URL=$CI_JOB_URL"
    - echo "CI_JOB_STARTED_AT=$CI_JOB_STARTED_AT"
    - echo "CI_KUBERNETES_ACTIVE=$CI_KUBERNETES_ACTIVE"
    - echo "CI_NODE_INDEX=$CI_NODE_INDEX"
    - echo "CI_NODE_TOTAL=$CI_NODE_TOTAL"
    - echo "CI_OPEN_MERGE_REQUESTS=$CI_OPEN_MERGE_REQUESTS"
    - echo "CI_PAGES_DOMAIN=$CI_PAGES_DOMAIN"
    - echo "CI_PAGES_URL=$CI_PAGES_URL"
    - echo "CI_PIPELINE_ID=$CI_PIPELINE_ID"
    - echo "CI_PIPELINE_IID=$CI_PIPELINE_IID"
    - echo "CI_PIPELINE_SOURCE=$CI_PIPELINE_SOURCE"
    - echo "CI_PIPELINE_TRIGGERED=$CI_PIPELINE_TRIGGERED"
    - echo "CI_PIPELINE_URL=$CI_PIPELINE_URL"
    - echo "CI_PIPELINE_CREATED_AT=$CI_PIPELINE_CREATED_AT"
    - echo "CI_PIPELINE_NAME=$CI_PIPELINE_NAME"
    - echo "CI_PROJECT_DIR=$CI_PROJECT_DIR"
    - echo "CI_PROJECT_ID=$CI_PROJECT_ID"
    - echo "CI_PROJECT_NAME=$CI_PROJECT_NAME"
    - echo "CI_PROJECT_NAMESPACE=$CI_PROJECT_NAMESPACE"
    - echo "CI_PROJECT_NAMESPACE_ID=$CI_PROJECT_NAMESPACE_ID"
    - echo "CI_PROJECT_PATH_SLUG=$CI_PROJECT_PATH_SLUG"
    - echo "CI_PROJECT_PATH=$CI_PROJECT_PATH"
    - echo "CI_PROJECT_REPOSITORY_LANGUAGES=$CI_PROJECT_REPOSITORY_LANGUAGES"
    - echo "CI_PROJECT_ROOT_NAMESPACE=$CI_PROJECT_ROOT_NAMESPACE"
    - echo "CI_PROJECT_TITLE=$CI_PROJECT_TITLE"
    - echo "CI_PROJECT_DESCRIPTION=$CI_PROJECT_DESCRIPTION"
    - echo "CI_PROJECT_URL=$CI_PROJECT_URL"
    - echo "CI_PROJECT_VISIBILITY=$CI_PROJECT_VISIBILITY"
    - echo "CI_PROJECT_CLASSIFICATION_LABEL=$CI_PROJECT_CLASSIFICATION_LABEL"
    - echo "CI_REGISTRY=$CI_REGISTRY"
    - echo "CI_REGISTRY_IMAGE=$CI_REGISTRY_IMAGE"
    - echo "CI_REGISTRY_PASSWORD=$CI_REGISTRY_PASSWORD"
    - echo "CI_REGISTRY_USER=$CI_REGISTRY_USER"
    - echo "CI_RELEASE_DESCRIPTION=$CI_RELEASE_DESCRIPTION"
    - echo "CI_REPOSITORY_URL=$CI_REPOSITORY_URL"
    - echo "CI_RUNNER_DESCRIPTION=$CI_RUNNER_DESCRIPTION"
    - echo "CI_RUNNER_EXECUTABLE_ARCH=$CI_RUNNER_EXECUTABLE_ARCH"
    - echo "CI_RUNNER_ID=$CI_RUNNER_ID"
    - echo "CI_RUNNER_REVISION=$CI_RUNNER_REVISION"
    - echo "CI_RUNNER_SHORT_TOKEN=$CI_RUNNER_SHORT_TOKEN"
    - echo "CI_RUNNER_TAGS=$CI_RUNNER_TAGS"
    - echo "CI_RUNNER_VERSION=$CI_RUNNER_VERSION"
    - echo "CI_SERVER_FQDN=$CI_SERVER_FQDN"
    - echo "CI_SERVER_HOST=$CI_SERVER_HOST"
    - echo "CI_SERVER_NAME=$CI_SERVER_NAME"
    - echo "CI_SERVER_PORT=$CI_SERVER_PORT"
    - echo "CI_SERVER_PROTOCOL=$CI_SERVER_PROTOCOL"
    - echo "CI_SERVER_SHELL_SSH_HOST=$CI_SERVER_SHELL_SSH_HOST"
    - echo "CI_SERVER_SHELL_SSH_PORT=$CI_SERVER_SHELL_SSH_PORT"
    - echo "CI_SERVER_REVISION=$CI_SERVER_REVISION"
    - echo "CI_SERVER_TLS_CA_FILE=$CI_SERVER_TLS_CA_FILE"
    - echo "CI_SERVER_TLS_CERT_FILE=$CI_SERVER_TLS_CERT_FILE"
    - echo "CI_SERVER_TLS_KEY_FILE=$CI_SERVER_TLS_KEY_FILE"
    - echo "CI_SERVER_URL=$CI_SERVER_URL"
    - echo "CI_SERVER_VERSION_MAJOR=$CI_SERVER_VERSION_MAJOR"
    - echo "CI_SERVER_VERSION_MINOR=$CI_SERVER_VERSION_MINOR"
    - echo "CI_SERVER_VERSION_PATCH=$CI_SERVER_VERSION_PATCH"
    - echo "CI_SERVER_VERSION=$CI_SERVER_VERSION"
    - echo "CI_SERVER=$CI_SERVER"
    - echo "CI_SHARED_ENVIRONMENT=$CI_SHARED_ENVIRONMENT"
    - echo "CI_TEMPLATE_REGISTRY_HOST=$CI_TEMPLATE_REGISTRY_HOST"
    - echo "CI_TRIGGER_SHORT_TOKEN=$CI_TRIGGER_SHORT_TOKEN"
    - echo "GITLAB_CI=$GITLAB_CI"
    - echo "GITLAB_FEATURES=$GITLAB_FEATURES"
    - echo "GITLAB_USER_EMAIL=$GITLAB_USER_EMAIL"
    - echo "GITLAB_USER_ID=$GITLAB_USER_ID"
    - echo "GITLAB_USER_LOGIN=$GITLAB_USER_LOGIN"

print-ci-merge-request-variables:
  stage: merge-request-variables
  script:
    - echo "CI_MERGE_REQUEST_APPROVED= $CI_MERGE_REQUEST_APPROVED"
    - echo "CI_MERGE_REQUEST_ASSIGNEES= $CI_MERGE_REQUEST_ASSIGNEES"
    - echo "CI_MERGE_REQUEST_DIFF_BASE_SHA= $CI_MERGE_REQUEST_DIFF_BASE_SHA"
    - echo "CI_MERGE_REQUEST_DIFF_ID= $CI_MERGE_REQUEST_DIFF_ID"
    - echo "CI_MERGE_REQUEST_EVENT_TYPE= $CI_MERGE_REQUEST_EVENT_TYPE"
    - echo "CI_MERGE_REQUEST_DESCRIPTION= $CI_MERGE_REQUEST_DESCRIPTION"
    - echo "CI_MERGE_REQUEST_DESCRIPTION_IS_TRUNCATED= $CI_MERGE_REQUEST_DESCRIPTION_IS_TRUNCATED"
    - echo "CI_MERGE_REQUEST_ID= $CI_MERGE_REQUEST_ID"
    - echo "CI_MERGE_REQUEST_IID= $CI_MERGE_REQUEST_IID"
    - echo "CI_MERGE_REQUEST_LABELS= $CI_MERGE_REQUEST_LABELS"
    - echo "CI_MERGE_REQUEST_MILESTONE= $CI_MERGE_REQUEST_MILESTONE"
    - echo "CI_MERGE_REQUEST_PROJECT_ID= $CI_MERGE_REQUEST_PROJECT_ID"
    - echo "CI_MERGE_REQUEST_PROJECT_PATH= $CI_MERGE_REQUEST_PROJECT_PATH"
    - echo "CI_MERGE_REQUEST_PROJECT_URL= $CI_MERGE_REQUEST_PROJECT_URL"
    - echo "CI_MERGE_REQUEST_REF_PATH= $CI_MERGE_REQUEST_REF_PATH"
    - echo "CI_MERGE_REQUEST_SOURCE_BRANCH_NAME= $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME"
    - echo "CI_MERGE_REQUEST_SOURCE_BRANCH_PROTECTED= $CI_MERGE_REQUEST_SOURCE_BRANCH_PROTECTED"
    - echo "CI_MERGE_REQUEST_SOURCE_BRANCH_SHA= $CI_MERGE_REQUEST_SOURCE_BRANCH_SHA"
    - echo "CI_MERGE_REQUEST_SOURCE_PROJECT_ID= $CI_MERGE_REQUEST_SOURCE_PROJECT_ID"
    - echo "CI_MERGE_REQUEST_SOURCE_PROJECT_PATH= $CI_MERGE_REQUEST_SOURCE_PROJECT_PATH"
    - echo "CI_MERGE_REQUEST_SOURCE_PROJECT_URL= $CI_MERGE_REQUEST_SOURCE_PROJECT_URL"
    - echo "CI_MERGE_REQUEST_SQUASH_ON_MERGE= $CI_MERGE_REQUEST_SQUASH_ON_MERGE"
    - echo "CI_MERGE_REQUEST_TARGET_BRANCH_NAME= $CI_MERGE_REQUEST_TARGET_BRANCH_NAME"
    - echo "CI_MERGE_REQUEST_TARGET_BRANCH_PROTECTED= $CI_MERGE_REQUEST_TARGET_BRANCH_PROTECTED"
    - echo "CI_MERGE_REQUEST_TARGET_BRANCH_SHA= $CI_MERGE_REQUEST_TARGET_BRANCH_SHA"
    - echo "CI_MERGE_REQUEST_TITLE= $CI_MERGE_REQUEST_TITLE"

test-job:
  stage: test
  script:
    - echo "Global Variable= $GLOBAL_VARIABLE"
    - echo "Common URL= $COMMON_URL"
    - echo "Local Variable= $LOCAL_VARIABLE"
  variables: 
    LOCAL_VARIABLE: "This is a local variable for test-job"
    TEST_URL: "https://test.example.com"

deploy-job:
  stage: deploy
  script:
    - echo "Global Variable= $GLOBAL_VARIABLE"
    - echo "Common URL= $COMMON_URL"
    - echo "Deploy-specific Variable= $DEPLOY_URL"
  variables: 
    DEPLOY_URL: "https://deploy.example.com"
